### ISSUE TITLE
Update logs with tags

### ISSUE THREAD

**Issue by shadow7** [IntrepidPursuits/AndroidSkeleton#6]
What we currently have:
`08-22 18:57:47.222 V/BaseActivity: Lifecycle onCreate: org.remainnantucket.track.app.screens.route.RouteSelectActivity@9db4a61`

After an update:
`08-22 18:57:47.222 V/RouteSelectActivity@9db4a61: Lifecycle onCreate`

gist: https://gist.github.com/shadow7/e6f0fdfc822758c1bb2aaa6e8f20a27a

**Comment by f2rf2r** [comment]
Is the main difference here having the object hash in the tag instead of the message? I personally prefer not modifying the Timber tag to keeps the logs consistent.
